version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_book
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword     # Root password
      MYSQL_DATABASE: book_db     # Database to create
      MYSQL_USER: bookuser                # Non-root user to create
      MYSQL_PASSWORD: bookpassword        # Password for the user
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer_book
    restart: always
    ports:
      - "8087:8080"
